ДЗ 3
Alekdersan/homework1.2 pull request #1
Opened 2021-12-29 21:20 UTC by Alekdersan

2021-12-30 16:56 UTC, rmuhamedgaliev requested changes
Привет! Давай исправим замечания.

2021-12-30 16:56 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +        int clientOs2 = 0;// выбрать ОС для iOs
Лучше стараться избегать и не использовать цифры в названии переменных. В следующих заданиях такое не приму. Именование переменных, классов и методов очень важная часть работы, так как мы пишем код и читаем. Причем есть данные что читаем мы код больше чем пишем.

2021-12-30 16:56 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +        if (deliveryDistance <= 20) {
Формально задание выполнено. Но если изменить стартовое значение времени доставки, то придется меня другие параметры. Лучше сделать независимыми условиями 

`
int result = 1; 

if (deliveryDistance > 20) { 

result++; 

} 

if (deliveryDistance > 60 && deliveryDistance <= 100) { 

result++; 

}
`

И вывод в конце всех условий, чтобы избежать дублирования кода

2021-12-30 16:56 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +        switch (monthNumber) {
В операторе switch можно пропускать некоторые условия, что бы оптимизировать понимание кода. Выглядит это так

```
switch (monthNumber) { 
case 12: 
case 1: 
case 2: 
System.out.println("Зима");
break; 
```

2021-12-30 16:56 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +
Пустые строки необходимо убрать. Аккуратный код залог безопасного рефакторинга

2021-12-31 04:51 UTC, Alekdersan commented on src/ru/skypro/Main.java
> +
Удалил пустые строки.

2021-12-31 04:53 UTC, Alekdersan commented on src/ru/skypro/Main.java
> +        switch (monthNumber) {
Отличное решение! Nice!
Усвоил, исправил.

2021-12-31 04:54 UTC, Alekdersan commented on src/ru/skypro/Main.java
> +        if (deliveryDistance <= 20) {
О, это реальное доходит до понимания со временем! Конечно! Усвоил.
Исправил.

2021-12-31 04:54 UTC, Alekdersan commented on src/ru/skypro/Main.java
> +        int clientOs2 = 0;// выбрать ОС для iOs
По всем кодам убрал в названии переменных цифры

2021-12-31 15:57 UTC, merged